### ISSUE TITLE
Gem 'bcrypt', platforms: :ruby

### ISSUE THREAD

**Issue by DavidLuptak** [MartinStyk/quotes-recommender#2]
Gemfile specifies the `gem 'bcrypt', platforms: :ruby`, which is for platforms outside Windows, but I think this gem is not needed separately, since it is included under the `devise` gem (you can see it in the <Gemfile.lock> file).

Is it needed for Windows platform? Something like `gem 'bcrypt', platforms: :x64_mingw`?

Can you @MartinStyk check it out?

**Comment by MartinStyk** [comment]
i believe we can close this one:
gem 'bcrypt', platforms: :ruby is needed, 
gem 'bcrypt', platforms: :x64_mingw is somehow damaged and cause issues.
